owner: sniffingsugar
repo: status

sites:
  - name: Git-Server
    url: https://git.ucode.space
  - name: Docker-Registry
    url: https://registry.ucode.space
  - name: Cloud
    url: https://cloud.ucode.space
  - name: Wakapi
    url: https://time.ucode.space
  - name: gly.one (URL Shortener)
    url: https://gly.one
    assignees:
      - ucodelukas
      - ata-star
    

status-website:
  theme: night
  metaTags:
    - name: "color-scheme"
      content: "dark"
    - name: "robots"
      content: "noindex"
  cname: status.ucode.space
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ustatus
  introTitle: "**ucode.space** uptime status :)"
  navbar:
    - title: Status
      href: /

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/2 * * * *"
  
commitMessages:
  commitAuthorName: "uUpdate"
  commitAuthorEmail: "info@ucode.space"
