owner: sniffingsugar
repo: status

sites:
  - name: Git-Server
    url: https://git.ucode.space
  - name: Docker-Registry
    url: https://registry.ucode.space

status-website:
  theme: dark
  metaTags:
    - name: "color-scheme"
      content: "dark"
    - name: "robots"
      content: "noindex"
  cname: status.ucode.space
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: ustatus
  introTitle: "**ucode.space** uptime status :)"
  navbar:
    - title: Status
      href: /

commitMessages:
  commitAuthorName: "uUpdate"
  commitAuthorEmail: "info@ucode.space"
